<?php

namespace App\Http\Controllers;


class LocationController extends Controller
{
    public static function getCounties()
    {
        return [
            "Baringo",
            "Bomet",
            "Bungoma",
            "Busia",
            "Elgeyo Marakwet",
            "Embu",
            "Garissa",
            "Homa Bay",
            "Isiolo",
            "Kajiado",
            "Kakamega",
            "Kericho",
            "Kiambu",
            "Kilifi",
            "Kirinyaga",
            "Kisii",
            "Kisumu",
            "Kitui",
            "Kwale",
            "Laikipia",
            "Lamu",
            "Machakos",
            "Makueni",
            "Mandera",
            "Marsabit",
            "Meru",
            "Migori",
            "Mombasa",
            "Murang'a",
            "Nairobi",
            "Nakuru",
            "Nandi",
            "Narok",
            "Nyamira",
            "Nyandarua",
            "Nyeri",
            "Samburu",
            "Siaya",
            "Taita Taveta",
            "Tana River",
            "Tharaka Nithi",
            "Trans Nzoia",
            "Turkana",
            "Uasin Gishu",
            "Vihiga",
            "Wajir",
            "West Pokot"
        ];
    }
    public static function getSubCounties()
    {
        return [
            "Baringo Central",
            "Baringo North",
            "Baringo South",
            "Eldama Ravine",
            "Keiyo North",
            "Keiyo South",
            "Marakwet East",
            "Marakwet West",
            "Embu East",
            "Embu North",
            "Embu West",
            "Mbeere North",
            "Mbeere South",
            "Isinya",
            "Kajiado Central",
            "Kajiado East",
            "Kajiado North",
            "Kajiado South",
            "Kajiado West",
            "Kakamega Central",
            "Kakamega East",
            "Kakamega North",
            "Kakamega South",
            "Kakamega West",
            "Lugari",
            "Malava",
            "Likuyani",
            "Kilifi North",
            "Kilifi South",
            "Kaloleni",
            "Rabai",
            "Ganze",
            "Malindi",
            "Magarini",
            "Kitui Central",
            "Kitui East",
            "Kitui South",
            "Kitui West",
            "Mwingi Central",
            "Mwingi East",
            "Mwingi West",
            "Laikipia Central",
            "Laikipia East",
            "Laikipia North",
            "Laikipia West",
            "Lamu East",
            "Lamu West",
            "Meru Central",
            "Meru South",
            "Igembe Central",
            "Igembe North",
            "Igembe South",
            "Tigania East",
            "Tigania West",
            "Marsabit Central",
            "Marsabit North",
            "Marsabit South",
            "Marsabit West",
            "Mombasa Island",
            "Changamwe",
            "Jomvu",
            "Kisauni",
            "Likoni",
            "Nyali",
            "Nairobi West",
            "Nairobi East",
            "Nairobi North",
            "Dagoretti",
            "Lang’ata",
            "Kibra",
            "Kamukunji",
            "Embakasi",
            "Roysambu",
            "Kasarani",
            "Ruaraka",
            "Westlands",
            "Starehe",
            "Mathare"
        ];
    }
    public static function getCounstituency()
    {
        return  [
            "Changamwe",
            "Jomvu",
            "Kisauni",
            "Likoni",
            "Mvita",
            "Nyali",
            "Kinango",
            "Lunga Lunga",
            "Matuga",
            "Msambweni",
            "Ganze",
            "Kaloleni",
            "Kilifi North",
            "Kilifi South",
            "Magarini",
            "Malindi",
            "Bahari",
            "Rabai",
            "Lamu East",
            "Lamu West",
            "Tana River",
            "Tana North",
            "Bura",
            "Garissa Township",
            "Balambala",
            "Dadaab",
            "Fafi",
            "Ijara",
            "Lagdera",
            "Wajir East",
            "Wajir West",
            "Wajir North",
            "Wajir South",
            "Wajir West",
            "Mandera East",
            "Mandera North",
            "Mandera South",
            "Mandera West",
            "Banissa",
            "Marsabit",
            "Laisamis",
            "Moyale",
            "Isiolo North",
            "Isiolo South",
            "Meru Central",
            "Meru South",
            "Igembe Central",
            "Igembe North",
            "Igembe South",
            "Tigania East",
            "Tigania West",
            "Embu North",
            "Embu East",
            "Embu West",
            "Mbeere North",
            "Mbeere South",
            "Tharaka",
            "Nithi",
            "Chuka",
            "Igambang’ombe",
            "Maara",
            "Kitui Central",
            "Kitui East",
            "Kitui South",
            "Kitui West",
            "Mwingi Central",
            "Mwingi East",
            "Mwingi West",
            "Machakos Town",
            "Mavoko",
            "Masinga",
            "Yatta",
            "Kangundo",
            "Matungulu",
            "Kathiani",
            "Mbooni",
            "Kaiti",
            "Makueni",
            "Kilome",
            "Kibwezi East",
            "Kibwezi West",
            "Nairobi West",
            "Nairobi East",
            "Nairobi North",
            "Dagoretti North",
            "Dagoretti South",
            "Embakasi East",
            "Embakasi West",
            "Embakasi Central",
            "Embakasi South",
            "Embakasi North",
            "Kasarani",
            "Ruaraka",
            "Westlands",
            "Starehe",
            "Mathare",
            "Kibra",
            "Kamukunji",
            "Lang’ata"
        ];
    }
    public static function getWards()
    {
        return [
            // Nairobi County
            'Kitisuru',
            'Parklands/Highridge',
            'Karura',
            'Kangemi',
            'Mountain View',
            'Kilimani',
            'Kawangware',
            'Gatina',
            'Kileleshwa',
            'Kabiro',
            'Mutu-ini',
            'Ngando',
            'Riruta',
            'Uthiru/Ruthimitu',
            'Waithaka',
            'Karen',
            'Nairobi West',
            'Mugumu-ini',
            'South C',
            'Nyayo Highrise',
            'Laini Saba',
            'Lindi',
            'Makina',
            'Woodley/Kenyatta Golf Course',
            'Sarangombe',
            'Githurai',
            'Kahawa West',
            'Zimmerman',
            'Roysambu',
            'Kahawa',
            'Clay City',
            'Mwiki',
            'Kasarani',
            'Njiru',
            'Ruai',
            'Baba Dogo',
            'Utalii',
            'Mathare North',
            'Lucky Summer',
            'Korogocho',
            'Imara Daima',
            'Kwa Njenga',
            'Kwa Reuben',
            'Pipeline',
            'Kware',
            'Kariobangi North',
            'Dandora Area I',
            'Dandora Area II',
            'Dandora Area III',
            'Dandora Area IV',
            'Kayole North',
            'Kayole Central',
            'Kayole South',
            'Komarock',
            'Matopeni/Spring Valley',
            'Upper Savannah',
            'Lower Savannah',
            'Embakasi',
            'Utawala',
            'Mihango',
            'Umoja I',
            'Umoja II',
            'Mowlem',
            'Kariobangi South',
            'Maringo/Hamza',
            'Maringo/Hamza',
            'Viwandani',
            'Harambee',
            'Makongeni',
            'Pumwani',
            'Eastleigh North',
            'Eastleigh South',
            'Airbase',
            'California',
            'Ngara',
            'Nairobi Central',
            'Pangani',
            'Ziwani/Kariokor',
            'Landimawe',
            'Nairobi South',
            'Hospital',
            'Mabatini',
            'Huruma',
            'Ngei',
            'Mlango Kubwa',
            'Kiamaiko',

            // Kiambu County
            'Kikuyu',
            'Kabete',
            'Limuru',
            'Githunguri',
            'Juja',
            'Ruiru',
            'Thika Town',
            'Gatundu South',
            'Gatundu North',
            'Lari',

            // Mombasa County
            'Changamwe',
            'Jomvu',
            'Kisauni',
            'Nyali',
            'Likoni',
            'Mvita',

            // Kisumu County
            'Kisumu East',
            'Kisumu West',
            'Kisumu Central',
            'Nyando',
            'Muhoroni',
            'Seme',

            // Nakuru County
            'Nakuru East',
            'Nakuru West',
            'Naivasha',
            'Gilgil',
            'Subukia',
            'Molo',
            'Kuresoi North',
            'Kuresoi South',

            // Uasin Gishu County
            'Turbo',
            'Kesses',
            'Ainabkoi',
            'Kapseret',
            'Moiben',
            'Soy',

            // Machakos County
            'Machakos Town',
            'Mwala',
            'Kangundo',
            'Masinga',
            'Yatta',
            'Kathiani',

            // Nyeri County
            'Nyeri Town',
            'Othaya',
            'Tetu',
            'Mathira',
            'Mukurweini',

            // Meru County
            'Imenti North',
            'Imenti South',
            'Buuri',
            'Tigania West',
            'Tigania East',

            // Kakamega County
            'Lurambi',
            'Navakholo',
            'Malava',
            'Mumias East',
            'Mumias West',
            'Butere',

            // Bungoma County
            'Bungoma East',
            'Bungoma West',
            'Kanduyi',
            'Sirisia',
            'Kimilili',

            // Other additional wards
            'Kitui Central',
            'Moyale',
            'Taveta',
            'Kilifi South',
            'Kilifi North',
            'Kwale Central',
            'Narok North',
            'Narok South',
            'Bomet Central',
            'Bomet East',
            'Kericho Town',
            'Kipkelion East',
            'Embu North',
            'Embu East',
            'Mbeere South',
            'Isiolo Central',
            'Marsabit South',
            'Wajir East',
            'Mandera North',
            'Garissa Central',
            'Tana River West'
        ];
    }
}
